# Generated by Django 5.2.6 on 2026-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_category_image_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.IntegerField(default=12, help_text='Гарантийный срок в месяцах'),
        ),
    ]
