# Generated by Django 5.2.6 on 2026-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_warranty_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Производитель товара', max_length=100, null=True),
        ),
    ]
